version: '3.4'


services:
  go-server:
    image: golang
    container_name: "austem-server"
    build: ./
    command: ./app
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    container_name: "austem-db"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA = "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./.data/db:/data/db
    ports:
      - "5432:5432"


